[package]
name = "MewManager"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.1", features = ["derive"] }
nix = "0.26.2"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
